In [61]:
from tinygrad import Tensor, nn
import torch
import numpy as np

In [5]:
torch.manual_seed(1337);

In [23]:
dist = torch.distributions.Categorical(torch.tensor([[0.1, 0.2, 0.7], [0.3, 0.3, 0.4]]))

In [25]:
dist.probs.shape

torch.Size([2, 3])

In [41]:
action = torch.tensor([[0, 2], [2, 2], [0, 0]])
print(action.shape)
dist.log_prob(action)

torch.Size([3, 2])


tensor([[-2.3026, -0.9163],
        [-0.3567, -0.9163],
        [-2.3026, -1.2040]])

In [73]:
dist.entropy()

tensor([0.8018, 1.0889])

# Tinygrad log prob

In [54]:
def log_prob(logits, actions):
    actions = actions.unsqueeze(-1)
    value, log_pmf = Tensor._broadcasted(actions, logits)
    value = value[..., :1]
    return log_pmf.gather(value, -1).squeeze(-1)

In [78]:
def entropy(logits:Tensor, probs: Tensor):
    logits = logits.clip(np.finfo(np.float32).min.item(), np.finfo(np.float32).max.item())
    return -(probs * logits).sum(-1)

In [79]:
logits = Tensor(dist.logits.numpy())
probs = logits.exp()
action = Tensor([[0, 2], [2, 2], [0, 0]])

In [81]:
entropy(logits, probs).numpy()

array([0.80181855, 1.0889    ], dtype=float32)

array([[-2.3025851 , -0.9162907 ],
       [-0.35667497, -0.9162907 ],
       [-2.3025851 , -1.2039728 ]], dtype=float32)